# my-values/kibana-values.yaml

service:
  type: NodePort
  port: 5601

resources:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Explicitly set the environment variables Kibana and its hooks will use
extraEnvs:
  - name: ELASTICSEARCH_HOSTS
    value: "https://elasticsearch-master.logging:9200" # CRITICAL: Ensure this is a STRING
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials # The K8s secret name
        key: password                         # The key within that secret
  - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
    value: "/usr/share/kibana/config/certs/ca.crt"
  # Add other necessary env vars if Kibana needs them e.g. ELASTICSEARCH_SSL_VERIFICATIONMODE: "certificate"

# Volume mounts for the Elasticsearch CA Certificate

#extraVolumeMounts:
 # - name: elasticsearch-certs
 #   mountPath: /usr/share/kibana/config/certs
 #   readOnly: true
#extraVolumes:
#  - name: elasticsearch-certs
#    secret:
#      secretName: elasticsearch-master-certs # Secret containing ES CA cert

# If your chart has specific top-level keys for SSL that work, you can use them too,
# but env vars are often a reliable override.
# For example:
# elasticsearchSSL:
#   certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
#   verificationMode: "certificate"