# my-values/kibana-values.yaml

service:
  type: NodePort
  port: 5601

resources:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Configuration for Kibana itself regarding Elasticsearch connection
elasticsearchHosts: ["https://elasticsearch-master.logging:9200"] 

elasticsearchSSL:
  certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
  # verificationMode: "certificate" # Optional, but good practice

# Explicitly set the environment variables Kibana will use
# This often overrides or supplements other settings.
extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials # The K8s secret name
        key: password                         # The key within that secret
  # Some charts might need ELASTICSEARCH_HOSTS and SSL CA also as env vars
  # if the top-level keys don't translate automatically, or to be absolutely sure.
  - name: ELASTICSEARCH_HOSTS # Often an array, but some Kibana versions take comma-separated string
    value: "https://elasticsearch-master.logging:9200"
  - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
    value: "/usr/share/kibana/config/certs/ca.crt"

# Volume mounts for the Elasticsearch CA Certificate (this part is likely correct)
extraVolumeMounts:
  - name: elasticsearch-certs
    mountPath: /usr/share/kibana/config/certs
    readOnly: true
extraVolumes:
  - name: elasticsearch-certs
    secret:
      secretName: elasticsearch-master-certs