apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jennystar7703/monitoring-stack-k8.git' # YOUR REPO URL
    targetRevision: HEAD
    path: helm-charts/fluent-bit
    helm:
      valueFiles:
        - ../my-values/fluentbit-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true