apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jennystar7703/monitoring-stack-k8.git' # YOUR REPO URL
<<<<<<< HEAD
    #targetRevision: HEAD
    targetRevision: hotfix/EFK-setup
=======
    #targetRevision: hotfix/EFK-setup
    targetRevision: HEAD # Or 'main'
>>>>>>> hotfix/EFK-setup
    path: helm-charts/kibana
    helm:
      valueFiles:
        - ../../my-values/kibana-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true