apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jennystar7703/monitoring-stack-k8.git' # YOUR REPO URL
    targetRevision: HEAD
    path: helm-charts/kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml # Path to your values
      # Add this line to tell ArgoCD to skip CRD management
      skipCrds: true # <--- ADD THIS LINE
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring # Target namespace for Prometheus stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true