name: Apply ArgoCD Applications

on:
  push:
    branches:
      - main # Or 'master', or whatever your default branch is
    paths:
      - 'argocd-apps/**'
  workflow_dispatch:

jobs:
  apply_manifests:
    name: Apply ArgoCD App Manifests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig-data: ${{ secrets.KUBE_CONFIG_DATA }} # <---  input name
        
    - name: Apply ArgoCD Application manifests
      run: |
        kubectl config current-context # Verify context
        kubectl apply -n argocd -f argocd-apps/
        echo "ArgoCD Application manifests applied."